import BlurShader from "./BlurShader.js";
import CopyShader from "./CopyShader.js";
import GradientSubtractShader from "./GradientSubtractShader.js";
import PressureShader from "./PressureShader.js";
import VorticityShader from "./VorticityShader.js";
import CurlShader from "./CurlShader.js";
import DivergenceShader from "./DivergenceShader.js";
import AdvectionShader from "./AdvectionShader.js";
import SplatShader from "./SplatShader.js";
import SunraysShader from "./SunraysShader.js";
import SunRaysMaskShader from "./SunRaysMaskShader.js";
import BloomFinalShader from "./bloomFinalShader.js";
import BloomBlurShader from "./BloomBlurShader.js";
import BloomPrefilterShader from "./BloomPrefilterShader.js";
import CheckerboardShader from "./CheckerboardShader.js";
import ColorShader from "./ColorShader.js";
import ClearShader from "./ClearShader.js";
var blurShader = new BlurShader();
var copyShader = new CopyShader();
var clearShader = new ClearShader();
var colorShader = new ColorShader();
var checkerboardShader = new CheckerboardShader();
var bloomPrefilterShader = new BloomPrefilterShader();
var bloomBlurShader = new BloomBlurShader();
var bloomFinalShader = new BloomFinalShader();
var sunraysMaskShader = new SunRaysMaskShader();
var sunraysShader = new SunraysShader();
var splatShader = new SplatShader();
var advectionShader = new AdvectionShader();
var divergenceShader = new DivergenceShader();
var curlShader = new CurlShader();
var vorticityShader = new VorticityShader();
var pressureShader = new PressureShader();
var gradientSubtractShader = new GradientSubtractShader();
export { checkerboardShader, bloomPrefilterShader, clearShader, bloomBlurShader, blurShader, copyShader, colorShader, sunraysMaskShader, gradientSubtractShader, pressureShader, vorticityShader, curlShader, divergenceShader, advectionShader, splatShader, sunraysShader, bloomFinalShader, };
