var config = {
    simResolution: 128,
    dyeResolution: 1024,
    CAPTURE_RESOLUTION: 512,
    densityDissipation: 1,
    velocityDissipation: 0.2,
    pressure: 0.8,
    pressureIterations: 20,
    curl: 30,
    splatRadius: 0.25,
    splatForce: 6000,
    shading: true,
    colorful: true,
    colorUpdateSpeed: 10,
    paused: false,
    backGroundColor: { r: 0, g: 0, b: 0 },
    transparent: false,
    bloom: true,
    bloomIterations: 8,
    bloomResolution: 256,
    bloomIntensity: 0.8,
    bloomThreshold: 0.6,
    bloomSoftKnee: 0.7,
    sunrays: false,
    sunraysResolution: 196,
    sunraysWeigth: 1.0,
    onlyHover: true,
};
export default config;
